// Code generated by go-swagger; DO NOT EDIT.

package user_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteUserV1Params creates a new DeleteUserV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteUserV1Params() *DeleteUserV1Params {
	return &DeleteUserV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserV1ParamsWithTimeout creates a new DeleteUserV1Params object
// with the ability to set a timeout on a request.
func NewDeleteUserV1ParamsWithTimeout(timeout time.Duration) *DeleteUserV1Params {
	return &DeleteUserV1Params{
		timeout: timeout,
	}
}

// NewDeleteUserV1ParamsWithContext creates a new DeleteUserV1Params object
// with the ability to set a context for a request.
func NewDeleteUserV1ParamsWithContext(ctx context.Context) *DeleteUserV1Params {
	return &DeleteUserV1Params{
		Context: ctx,
	}
}

// NewDeleteUserV1ParamsWithHTTPClient creates a new DeleteUserV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteUserV1ParamsWithHTTPClient(client *http.Client) *DeleteUserV1Params {
	return &DeleteUserV1Params{
		HTTPClient: client,
	}
}

/*
DeleteUserV1Params contains all the parameters to send to the API endpoint

	for the delete user v1 operation.

	Typically these are written to a http.Request.
*/
type DeleteUserV1Params struct {

	/* UserUUID.

	   User UUID.
	*/
	UserUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete user v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserV1Params) WithDefaults() *DeleteUserV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete user v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete user v1 params
func (o *DeleteUserV1Params) WithTimeout(timeout time.Duration) *DeleteUserV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user v1 params
func (o *DeleteUserV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user v1 params
func (o *DeleteUserV1Params) WithContext(ctx context.Context) *DeleteUserV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user v1 params
func (o *DeleteUserV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user v1 params
func (o *DeleteUserV1Params) WithHTTPClient(client *http.Client) *DeleteUserV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user v1 params
func (o *DeleteUserV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserUUID adds the userUUID to the delete user v1 params
func (o *DeleteUserV1Params) WithUserUUID(userUUID string) *DeleteUserV1Params {
	o.SetUserUUID(userUUID)
	return o
}

// SetUserUUID adds the userUuid to the delete user v1 params
func (o *DeleteUserV1Params) SetUserUUID(userUUID string) {
	o.UserUUID = userUUID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param user_uuid
	qrUserUUID := o.UserUUID
	qUserUUID := qrUserUUID
	if qUserUUID != "" {

		if err := r.SetQueryParam("user_uuid", qUserUUID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
