// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIBulkFileLabelItem api bulk file label item
//
// swagger:model api.BulkFileLabelItem
type APIBulkFileLabelItem struct {

	// The name of the lookup file
	// Required: true
	Filename *string `json:"filename"`

	// The labels to add/remove/replace (max 10 labels, max 60 chars each)
	// Required: true
	Labels []string `json:"labels"`
}

// Validate validates this api bulk file label item
func (m *APIBulkFileLabelItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilename(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIBulkFileLabelItem) validateFilename(formats strfmt.Registry) error {

	if err := validate.Required("filename", "body", m.Filename); err != nil {
		return err
	}

	return nil
}

func (m *APIBulkFileLabelItem) validateLabels(formats strfmt.Registry) error {

	if err := validate.Required("labels", "body", m.Labels); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api bulk file label item based on context it is used
func (m *APIBulkFileLabelItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIBulkFileLabelItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIBulkFileLabelItem) UnmarshalBinary(b []byte) error {
	var res APIBulkFileLabelItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
