// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DomainOnPrem domain on prem
//
// swagger:model domain.OnPrem
type DomainOnPrem struct {

	// host group id
	// Required: true
	HostGroupID *string `json:"host_group_id"`

	// Allows internal calls to not strictly validate certificates
	InsecureSkipVerify bool `json:"insecure_skip_verify,omitempty"`

	// Internal proxy to route requests
	ProxyURL string `json:"proxy_url,omitempty"`
}

// Validate validates this domain on prem
func (m *DomainOnPrem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHostGroupID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DomainOnPrem) validateHostGroupID(formats strfmt.Registry) error {

	if err := validate.Required("host_group_id", "body", m.HostGroupID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this domain on prem based on context it is used
func (m *DomainOnPrem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DomainOnPrem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainOnPrem) UnmarshalBinary(b []byte) error {
	var res DomainOnPrem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
