// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FwmgrMsaAPIFiltersSpec fwmgr msa API filters spec
//
// swagger:model fwmgr.msa.APIFiltersSpec
type FwmgrMsaAPIFiltersSpec struct {

	// filters
	// Required: true
	Filters map[string]string `json:"filters"`

	// other bucket
	// Required: true
	OtherBucket *bool `json:"other_bucket"`

	// other bucket key
	// Required: true
	OtherBucketKey *string `json:"other_bucket_key"`
}

// Validate validates this fwmgr msa API filters spec
func (m *FwmgrMsaAPIFiltersSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOtherBucket(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOtherBucketKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FwmgrMsaAPIFiltersSpec) validateFilters(formats strfmt.Registry) error {

	if err := validate.Required("filters", "body", m.Filters); err != nil {
		return err
	}

	return nil
}

func (m *FwmgrMsaAPIFiltersSpec) validateOtherBucket(formats strfmt.Registry) error {

	if err := validate.Required("other_bucket", "body", m.OtherBucket); err != nil {
		return err
	}

	return nil
}

func (m *FwmgrMsaAPIFiltersSpec) validateOtherBucketKey(formats strfmt.Registry) error {

	if err := validate.Required("other_bucket_key", "body", m.OtherBucketKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this fwmgr msa API filters spec based on context it is used
func (m *FwmgrMsaAPIFiltersSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FwmgrMsaAPIFiltersSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FwmgrMsaAPIFiltersSpec) UnmarshalBinary(b []byte) error {
	var res FwmgrMsaAPIFiltersSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
