// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IntegrationExposureUserGetUserInventory integration exposure user get user inventory
//
// swagger:model Integration_Exposure_User_GetUserInventory
type IntegrationExposureUserGetUserInventory struct {

	// Alias
	// Required: true
	// Min Length: 1
	Alias *string `json:"alias"`

	// Id
	// Required: true
	ID *string `json:"id"`

	// Name
	// Required: true
	// Min Length: 1
	Name *string `json:"name"`
}

// Validate validates this integration exposure user get user inventory
func (m *IntegrationExposureUserGetUserInventory) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlias(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IntegrationExposureUserGetUserInventory) validateAlias(formats strfmt.Registry) error {

	if err := validate.Required("alias", "body", m.Alias); err != nil {
		return err
	}

	if err := validate.MinLength("alias", "body", *m.Alias, 1); err != nil {
		return err
	}

	return nil
}

func (m *IntegrationExposureUserGetUserInventory) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *IntegrationExposureUserGetUserInventory) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this integration exposure user get user inventory based on context it is used
func (m *IntegrationExposureUserGetUserInventory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IntegrationExposureUserGetUserInventory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IntegrationExposureUserGetUserInventory) UnmarshalBinary(b []byte) error {
	var res IntegrationExposureUserGetUserInventory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
