// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Meta1b17f50c67bc43d381dd879591114299 meta 1b17f50c67bc43d381dd879591114299
//
// swagger:model Meta_1b17f50c67bc43d381dd879591114299
type Meta1b17f50c67bc43d381dd879591114299 struct {

	// pagination
	Pagination *Pagination16d85ed3c0cd47e195f15cd4a11ec032 `json:"pagination,omitempty"`

	// Query time
	QueryTime *float64 `json:"query_time,omitempty"`

	// Trace id
	// Min Length: 1
	TraceID *string `json:"trace_id,omitempty"`
}

// Validate validates this meta 1b17f50c67bc43d381dd879591114299
func (m *Meta1b17f50c67bc43d381dd879591114299) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTraceID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Meta1b17f50c67bc43d381dd879591114299) validatePagination(formats strfmt.Registry) error {
	if swag.IsZero(m.Pagination) { // not required
		return nil
	}

	if m.Pagination != nil {
		if err := m.Pagination.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pagination")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pagination")
			}
			return err
		}
	}

	return nil
}

func (m *Meta1b17f50c67bc43d381dd879591114299) validateTraceID(formats strfmt.Registry) error {
	if swag.IsZero(m.TraceID) { // not required
		return nil
	}

	if err := validate.MinLength("trace_id", "body", *m.TraceID, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this meta 1b17f50c67bc43d381dd879591114299 based on the context it is used
func (m *Meta1b17f50c67bc43d381dd879591114299) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePagination(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Meta1b17f50c67bc43d381dd879591114299) contextValidatePagination(ctx context.Context, formats strfmt.Registry) error {

	if m.Pagination != nil {

		if swag.IsZero(m.Pagination) { // not required
			return nil
		}

		if err := m.Pagination.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pagination")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pagination")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Meta1b17f50c67bc43d381dd879591114299) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Meta1b17f50c67bc43d381dd879591114299) UnmarshalBinary(b []byte) error {
	var res Meta1b17f50c67bc43d381dd879591114299
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
