// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RisksUnionCloudRisk risks union cloud risk
//
// swagger:model risks.UnionCloudRisk
type RisksUnionCloudRisk struct {

	// account id
	// Required: true
	AccountID *string `json:"account_id"`

	// account name
	// Required: true
	AccountName *string `json:"account_name"`

	// asset gcrn
	// Required: true
	AssetGcrn *string `json:"asset_gcrn"`

	// asset id
	// Required: true
	AssetID *string `json:"asset_id"`

	// asset name
	// Required: true
	AssetName *string `json:"asset_name"`

	// asset region
	AssetRegion string `json:"asset_region,omitempty"`

	// asset tags
	AssetTags []string `json:"asset_tags"`

	// asset type
	// Required: true
	AssetType *string `json:"asset_type"`

	// cid
	// Required: true
	Cid *string `json:"cid"`

	// cloud groups
	// Required: true
	CloudGroups []string `json:"cloud_groups"`

	// comment
	// Required: true
	Comment []*RiskComments `json:"comment"`

	// crn
	// Required: true
	Crn *string `json:"crn"`

	// disabled
	// Required: true
	Disabled *bool `json:"disabled"`

	// first seen
	// Required: true
	// Format: date-time
	FirstSeen *strfmt.DateTime `json:"first_seen"`

	// id
	// Required: true
	ID *string `json:"id"`

	// insight categories
	InsightCategories []string `json:"insight_categories"`

	// last seen
	// Format: date-time
	LastSeen strfmt.DateTime `json:"last_seen,omitempty"`

	// provider
	// Required: true
	Provider *string `json:"provider"`

	// resolved at
	// Format: date-time
	ResolvedAt strfmt.DateTime `json:"resolved_at,omitempty"`

	// risk factors
	RiskFactors []RisksRiskInterface `json:"risk_factors"`

	// rule description
	// Required: true
	RuleDescription *string `json:"rule_description"`

	// rule id
	// Required: true
	RuleID *string `json:"rule_id"`

	// rule name
	// Required: true
	RuleName *string `json:"rule_name"`

	// score
	// Required: true
	Score *int32 `json:"score"`

	// service category
	// Required: true
	ServiceCategory *string `json:"service_category"`

	// severity
	// Required: true
	Severity *string `json:"severity"`

	// silent
	// Required: true
	Silent *bool `json:"silent"`

	// status
	// Required: true
	Status *string `json:"status"`

	// suppression
	Suppression *RiskSuppression `json:"suppression,omitempty"`
}

// Validate validates this risks union cloud risk
func (m *RisksUnionCloudRisk) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAccountName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssetGcrn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssetID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssetName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssetType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCloudGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateComment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCrn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDisabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFirstSeen(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSeen(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResolvedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRuleDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRuleID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRuleName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScore(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServiceCategory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeverity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSilent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuppression(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RisksUnionCloudRisk) validateAccountID(formats strfmt.Registry) error {

	if err := validate.Required("account_id", "body", m.AccountID); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateAccountName(formats strfmt.Registry) error {

	if err := validate.Required("account_name", "body", m.AccountName); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateAssetGcrn(formats strfmt.Registry) error {

	if err := validate.Required("asset_gcrn", "body", m.AssetGcrn); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateAssetID(formats strfmt.Registry) error {

	if err := validate.Required("asset_id", "body", m.AssetID); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateAssetName(formats strfmt.Registry) error {

	if err := validate.Required("asset_name", "body", m.AssetName); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateAssetType(formats strfmt.Registry) error {

	if err := validate.Required("asset_type", "body", m.AssetType); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateCid(formats strfmt.Registry) error {

	if err := validate.Required("cid", "body", m.Cid); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateCloudGroups(formats strfmt.Registry) error {

	if err := validate.Required("cloud_groups", "body", m.CloudGroups); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateComment(formats strfmt.Registry) error {

	if err := validate.Required("comment", "body", m.Comment); err != nil {
		return err
	}

	for i := 0; i < len(m.Comment); i++ {
		if swag.IsZero(m.Comment[i]) { // not required
			continue
		}

		if m.Comment[i] != nil {
			if err := m.Comment[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("comment" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("comment" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RisksUnionCloudRisk) validateCrn(formats strfmt.Registry) error {

	if err := validate.Required("crn", "body", m.Crn); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateDisabled(formats strfmt.Registry) error {

	if err := validate.Required("disabled", "body", m.Disabled); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateFirstSeen(formats strfmt.Registry) error {

	if err := validate.Required("first_seen", "body", m.FirstSeen); err != nil {
		return err
	}

	if err := validate.FormatOf("first_seen", "body", "date-time", m.FirstSeen.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateLastSeen(formats strfmt.Registry) error {
	if swag.IsZero(m.LastSeen) { // not required
		return nil
	}

	if err := validate.FormatOf("last_seen", "body", "date-time", m.LastSeen.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateProvider(formats strfmt.Registry) error {

	if err := validate.Required("provider", "body", m.Provider); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateResolvedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ResolvedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("resolved_at", "body", "date-time", m.ResolvedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateRuleDescription(formats strfmt.Registry) error {

	if err := validate.Required("rule_description", "body", m.RuleDescription); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateRuleID(formats strfmt.Registry) error {

	if err := validate.Required("rule_id", "body", m.RuleID); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateRuleName(formats strfmt.Registry) error {

	if err := validate.Required("rule_name", "body", m.RuleName); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateScore(formats strfmt.Registry) error {

	if err := validate.Required("score", "body", m.Score); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateServiceCategory(formats strfmt.Registry) error {

	if err := validate.Required("service_category", "body", m.ServiceCategory); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateSeverity(formats strfmt.Registry) error {

	if err := validate.Required("severity", "body", m.Severity); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateSilent(formats strfmt.Registry) error {

	if err := validate.Required("silent", "body", m.Silent); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *RisksUnionCloudRisk) validateSuppression(formats strfmt.Registry) error {
	if swag.IsZero(m.Suppression) { // not required
		return nil
	}

	if m.Suppression != nil {
		if err := m.Suppression.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("suppression")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("suppression")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this risks union cloud risk based on the context it is used
func (m *RisksUnionCloudRisk) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateComment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSuppression(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RisksUnionCloudRisk) contextValidateComment(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Comment); i++ {

		if m.Comment[i] != nil {

			if swag.IsZero(m.Comment[i]) { // not required
				return nil
			}

			if err := m.Comment[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("comment" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("comment" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RisksUnionCloudRisk) contextValidateSuppression(ctx context.Context, formats strfmt.Registry) error {

	if m.Suppression != nil {

		if swag.IsZero(m.Suppression) { // not required
			return nil
		}

		if err := m.Suppression.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("suppression")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("suppression")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RisksUnionCloudRisk) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RisksUnionCloudRisk) UnmarshalBinary(b []byte) error {
	var res RisksUnionCloudRisk
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
