// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TypesStruct types struct
//
// swagger:model types.Struct
type TypesStruct struct {

	// fields
	// Required: true
	Fields map[string]TypesValue `json:"Fields"`
}

// Validate validates this types struct
func (m *TypesStruct) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFields(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TypesStruct) validateFields(formats strfmt.Registry) error {

	if err := validate.Required("Fields", "body", m.Fields); err != nil {
		return err
	}

	for k := range m.Fields {

		if err := validate.Required("Fields"+"."+k, "body", m.Fields[k]); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this types struct based on context it is used
func (m *TypesStruct) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TypesStruct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TypesStruct) UnmarshalBinary(b []byte) error {
	var res TypesStruct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
