builds:
  - id: falcon_sensor_download
    binary: falcon_sensor_download
    main: ./examples/falcon_sensor_download/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_cleanup_pods
    binary: falcon_cleanup_pods
    main: ./examples/falcon_cleanup_pods
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_cspm_ioms
    binary: falcon_cspm_ioms
    main: ./examples/falcon_cspm_ioms
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_detection_details
    binary: falcon_detection_details
    main: ./examples/falcon_detection_details
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_discover_host_details
    binary: falcon_discover_host_details
    main: ./examples/falcon_discover_host_details
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_event_stream
    binary: falcon_event_stream
    main: ./examples/falcon_event_stream
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_get_cid
    binary: falcon_get_cid
    main: ./examples/falcon_get_cid
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_iocs
    binary: falcon_iocs
    main: ./examples/falcon_iocs
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_host_details
    binary: falcon_host_details
    main: ./examples/falcon_host_details
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_registry_token
    binary: falcon_registry_token
    main: ./examples/falcon_registry_token
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_rtr_read_only_command
    binary: falcon_rtr_read_only_command
    main: ./examples/falcon_rtr_read_only_command
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_rtr_admin_create_and_run_script
    binary: falcon_rtr_admin_create_and_run_script
    main: ./examples/falcon_rtr_admin_create_and_run_script
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_spotlight_vulnerabilities
    binary: falcon_spotlight_vulnerabilities
    main: ./examples/falcon_spotlight_vulnerabilities
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_supported_kernels
    binary: falcon_supported_kernels
    main: ./examples/falcon_supported_kernels
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_zta
    binary: falcon_zta
    main: ./examples/falcon_zta
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_intel_indicators
    binary: falcon_intel_indicators
    main: ./examples/falcon_intel_indicators
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_intel_rules_download
    binary: falcon_intel_rules_download
    main: ./examples/falcon_intel_rules_download
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
- name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "darwin" }}macOS
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - id: falcon_sensor_download
    package_name: gofalcon-utils
    maintainer: integrations@crowdstrike.com

    file_name_template: >-
      {{ .ProjectName }}-
      {{ .Version }}-
      {{ .Release }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i686
      {{- else if eq .Arch "arm" }}aarch32
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}

    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: examples/falcon_sensor_download
        dst: /usr/share/doc/gofalcon/falcon_sensor_download.md
      - src: examples/falcon_cleanup_pods
        dst: /usr/share/doc/gofalcon/falcon_cleanup_pods
      - src: examples/falcon_cspm_ioms
        dst: /usr/share/doc/gofalcon/falcon_cspm_ioms
      - src: examples/falcon_detection_details
        dst: /usr/share/doc/gofalcon/falcon_detection_details
      - src: examples/falcon_discover_host_details
        dst: /usr/share/doc/gofalcon/falcon_discover_host_details
      - src: examples/falcon_event_stream
        dst: /usr/share/doc/gofalcon/falcon_event_stream
      - src: examples/falcon_get_cid
        dst: /usr/share/doc/gofalcon/falcon_get_cid
      - src: examples/falcon_iocs
        dst: /usr/share/doc/gofalcon/falcon_iocs
      - src: examples/falcon_host_details
        dst: /usr/share/doc/gofalcon/falcon_host_details
      - src: examples/falcon_registry_token
        dst: /usr/share/doc/gofalcon/falcon_registry_token
      - src: examples/falcon_spotlight_vulnerabilities
        dst: /usr/share/doc/gofalcon/falcon_spotlight_vulnerabilities
      - src: examples/falcon_supported_kernels
        dst: /usr/share/doc/gofalcon/falcon_supported_kernels
      - src: examples/falcon_zta
        dst: /usr/share/doc/gofalcon/falcon_zta
      - src: examples/falcon_intel_indicators
        dst: /usr/share/doc/gofalcon/falcon_intel_indicators

    homepage: github.com/crowdstrike/gofalcon
    license: MIT
    description: Golang-based SDK to CrowdStrike's APIs
    release: 1
