builds:
  - id: falcon_sensor_download
    binary: falcon_sensor_download
    main: ./examples/falcon_sensor_download/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_cleanup_pods
    binary: falcon_cleanup_pods
    main: ./examples/falcon_cleanup_pods
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_event_stream
    binary: falcon_event_stream
    main: ./examples/falcon_event_stream
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: falcon_iocs
    binary: falcon_iocs
    main: ./examples/falcon_iocs
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - id: falcon_sensor_download
    package_name: gofalcon-utils

    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Release }}.{{ .Arch }}"
    replacements:
      386: i686
      amd64: x86_64
      arm: aarch32
      arm64: aarch64

    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: examples/falcon_sensor_download
        dst: /usr/share/doc/gofalcon/falcon_sensor_download.md
      - src: examples/falcon_cleanup_pods
        dst: /usr/share/doc/gofalcon/falcon_cleanup_pods
      - src: examples/falcon_event_stream
        dst: /usr/share/doc/gofalcon/falcon_event_stream
      - src: examples/falcon_iocs
        dst: /usr/share/doc/gofalcon/falcon_iocs

    homepage: github.com/crowdstrike/gofalcon
    license: MIT
    description: Golang-based SDK to CrowdStrike's APIs
    release: 1
