// Code generated by go-swagger; DO NOT EDIT.

package aidr_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAggregateDetectionsV1Params creates a new AggregateDetectionsV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAggregateDetectionsV1Params() *AggregateDetectionsV1Params {
	return &AggregateDetectionsV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewAggregateDetectionsV1ParamsWithTimeout creates a new AggregateDetectionsV1Params object
// with the ability to set a timeout on a request.
func NewAggregateDetectionsV1ParamsWithTimeout(timeout time.Duration) *AggregateDetectionsV1Params {
	return &AggregateDetectionsV1Params{
		timeout: timeout,
	}
}

// NewAggregateDetectionsV1ParamsWithContext creates a new AggregateDetectionsV1Params object
// with the ability to set a context for a request.
func NewAggregateDetectionsV1ParamsWithContext(ctx context.Context) *AggregateDetectionsV1Params {
	return &AggregateDetectionsV1Params{
		Context: ctx,
	}
}

// NewAggregateDetectionsV1ParamsWithHTTPClient creates a new AggregateDetectionsV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewAggregateDetectionsV1ParamsWithHTTPClient(client *http.Client) *AggregateDetectionsV1Params {
	return &AggregateDetectionsV1Params{
		HTTPClient: client,
	}
}

/*
AggregateDetectionsV1Params contains all the parameters to send to the API endpoint

	for the aggregate detections v1 operation.

	Typically these are written to a http.Request.
*/
type AggregateDetectionsV1Params struct {

	/* AgentID.

	   Filter by agent ID (see endpoint notes: some use the 64-hex AIAgent.Id, detections use the 32-hex SensorId)
	*/
	AgentID *string

	/* Limit.

	   Maximum number of results to return (1-500, default 50)
	*/
	Limit *int64

	/* Offset.

	   Pagination offset (0-1000)
	*/
	Offset *int64

	/* Product.

	   Filter by AI product name (e.g., CLAUDE_CODE, CURSOR)
	*/
	Product *string

	/* TimeRange.

	   Lookback period (e.g., 7d, 24h). Max 90d
	*/
	TimeRange *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the aggregate detections v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AggregateDetectionsV1Params) WithDefaults() *AggregateDetectionsV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the aggregate detections v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AggregateDetectionsV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) WithTimeout(timeout time.Duration) *AggregateDetectionsV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) WithContext(ctx context.Context) *AggregateDetectionsV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) WithHTTPClient(client *http.Client) *AggregateDetectionsV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentID adds the agentID to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) WithAgentID(agentID *string) *AggregateDetectionsV1Params {
	o.SetAgentID(agentID)
	return o
}

// SetAgentID adds the agentId to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) SetAgentID(agentID *string) {
	o.AgentID = agentID
}

// WithLimit adds the limit to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) WithLimit(limit *int64) *AggregateDetectionsV1Params {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) WithOffset(offset *int64) *AggregateDetectionsV1Params {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithProduct adds the product to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) WithProduct(product *string) *AggregateDetectionsV1Params {
	o.SetProduct(product)
	return o
}

// SetProduct adds the product to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) SetProduct(product *string) {
	o.Product = product
}

// WithTimeRange adds the timeRange to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) WithTimeRange(timeRange *string) *AggregateDetectionsV1Params {
	o.SetTimeRange(timeRange)
	return o
}

// SetTimeRange adds the timeRange to the aggregate detections v1 params
func (o *AggregateDetectionsV1Params) SetTimeRange(timeRange *string) {
	o.TimeRange = timeRange
}

// WriteToRequest writes these params to a swagger request
func (o *AggregateDetectionsV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AgentID != nil {

		// query param agent_id
		var qrAgentID string

		if o.AgentID != nil {
			qrAgentID = *o.AgentID
		}
		qAgentID := qrAgentID
		if qAgentID != "" {

			if err := r.SetQueryParam("agent_id", qAgentID); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Product != nil {

		// query param product
		var qrProduct string

		if o.Product != nil {
			qrProduct = *o.Product
		}
		qProduct := qrProduct
		if qProduct != "" {

			if err := r.SetQueryParam("product", qProduct); err != nil {
				return err
			}
		}
	}

	if o.TimeRange != nil {

		// query param time_range
		var qrTimeRange string

		if o.TimeRange != nil {
			qrTimeRange = *o.TimeRange
		}
		qTimeRange := qrTimeRange
		if qTimeRange != "" {

			if err := r.SetQueryParam("time_range", qTimeRange); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
