// Code generated by go-swagger; DO NOT EDIT.

package containment_allowlist_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// QueryContainmentAllowlistRulesReader is a Reader for the QueryContainmentAllowlistRules structure.
type QueryContainmentAllowlistRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryContainmentAllowlistRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryContainmentAllowlistRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewQueryContainmentAllowlistRulesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewQueryContainmentAllowlistRulesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewQueryContainmentAllowlistRulesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /customers/queries/containment-allowlist-rules/v1] QueryContainmentAllowlistRules", response, response.Code())
	}
}

// NewQueryContainmentAllowlistRulesOK creates a QueryContainmentAllowlistRulesOK with default headers values
func NewQueryContainmentAllowlistRulesOK() *QueryContainmentAllowlistRulesOK {
	return &QueryContainmentAllowlistRulesOK{}
}

/*
QueryContainmentAllowlistRulesOK describes a response with status code 200, with default header values.

OK
*/
type QueryContainmentAllowlistRulesOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.IpwhitelistQueryResponse
}

// IsSuccess returns true when this query containment allowlist rules o k response has a 2xx status code
func (o *QueryContainmentAllowlistRulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this query containment allowlist rules o k response has a 3xx status code
func (o *QueryContainmentAllowlistRulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query containment allowlist rules o k response has a 4xx status code
func (o *QueryContainmentAllowlistRulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this query containment allowlist rules o k response has a 5xx status code
func (o *QueryContainmentAllowlistRulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this query containment allowlist rules o k response a status code equal to that given
func (o *QueryContainmentAllowlistRulesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the query containment allowlist rules o k response
func (o *QueryContainmentAllowlistRulesOK) Code() int {
	return 200
}

func (o *QueryContainmentAllowlistRulesOK) Error() string {
	return fmt.Sprintf("[GET /customers/queries/containment-allowlist-rules/v1][%d] queryContainmentAllowlistRulesOK  %+v", 200, o.Payload)
}

func (o *QueryContainmentAllowlistRulesOK) String() string {
	return fmt.Sprintf("[GET /customers/queries/containment-allowlist-rules/v1][%d] queryContainmentAllowlistRulesOK  %+v", 200, o.Payload)
}

func (o *QueryContainmentAllowlistRulesOK) GetPayload() *models.IpwhitelistQueryResponse {
	return o.Payload
}

func (o *QueryContainmentAllowlistRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.IpwhitelistQueryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryContainmentAllowlistRulesForbidden creates a QueryContainmentAllowlistRulesForbidden with default headers values
func NewQueryContainmentAllowlistRulesForbidden() *QueryContainmentAllowlistRulesForbidden {
	return &QueryContainmentAllowlistRulesForbidden{}
}

/*
QueryContainmentAllowlistRulesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type QueryContainmentAllowlistRulesForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this query containment allowlist rules forbidden response has a 2xx status code
func (o *QueryContainmentAllowlistRulesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query containment allowlist rules forbidden response has a 3xx status code
func (o *QueryContainmentAllowlistRulesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query containment allowlist rules forbidden response has a 4xx status code
func (o *QueryContainmentAllowlistRulesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this query containment allowlist rules forbidden response has a 5xx status code
func (o *QueryContainmentAllowlistRulesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this query containment allowlist rules forbidden response a status code equal to that given
func (o *QueryContainmentAllowlistRulesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the query containment allowlist rules forbidden response
func (o *QueryContainmentAllowlistRulesForbidden) Code() int {
	return 403
}

func (o *QueryContainmentAllowlistRulesForbidden) Error() string {
	return fmt.Sprintf("[GET /customers/queries/containment-allowlist-rules/v1][%d] queryContainmentAllowlistRulesForbidden  %+v", 403, o.Payload)
}

func (o *QueryContainmentAllowlistRulesForbidden) String() string {
	return fmt.Sprintf("[GET /customers/queries/containment-allowlist-rules/v1][%d] queryContainmentAllowlistRulesForbidden  %+v", 403, o.Payload)
}

func (o *QueryContainmentAllowlistRulesForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *QueryContainmentAllowlistRulesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryContainmentAllowlistRulesTooManyRequests creates a QueryContainmentAllowlistRulesTooManyRequests with default headers values
func NewQueryContainmentAllowlistRulesTooManyRequests() *QueryContainmentAllowlistRulesTooManyRequests {
	return &QueryContainmentAllowlistRulesTooManyRequests{}
}

/*
QueryContainmentAllowlistRulesTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type QueryContainmentAllowlistRulesTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this query containment allowlist rules too many requests response has a 2xx status code
func (o *QueryContainmentAllowlistRulesTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query containment allowlist rules too many requests response has a 3xx status code
func (o *QueryContainmentAllowlistRulesTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query containment allowlist rules too many requests response has a 4xx status code
func (o *QueryContainmentAllowlistRulesTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this query containment allowlist rules too many requests response has a 5xx status code
func (o *QueryContainmentAllowlistRulesTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this query containment allowlist rules too many requests response a status code equal to that given
func (o *QueryContainmentAllowlistRulesTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the query containment allowlist rules too many requests response
func (o *QueryContainmentAllowlistRulesTooManyRequests) Code() int {
	return 429
}

func (o *QueryContainmentAllowlistRulesTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /customers/queries/containment-allowlist-rules/v1][%d] queryContainmentAllowlistRulesTooManyRequests  %+v", 429, o.Payload)
}

func (o *QueryContainmentAllowlistRulesTooManyRequests) String() string {
	return fmt.Sprintf("[GET /customers/queries/containment-allowlist-rules/v1][%d] queryContainmentAllowlistRulesTooManyRequests  %+v", 429, o.Payload)
}

func (o *QueryContainmentAllowlistRulesTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *QueryContainmentAllowlistRulesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryContainmentAllowlistRulesInternalServerError creates a QueryContainmentAllowlistRulesInternalServerError with default headers values
func NewQueryContainmentAllowlistRulesInternalServerError() *QueryContainmentAllowlistRulesInternalServerError {
	return &QueryContainmentAllowlistRulesInternalServerError{}
}

/*
QueryContainmentAllowlistRulesInternalServerError describes a response with status code 500, with default header values.

Unexpected Error
*/
type QueryContainmentAllowlistRulesInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this query containment allowlist rules internal server error response has a 2xx status code
func (o *QueryContainmentAllowlistRulesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query containment allowlist rules internal server error response has a 3xx status code
func (o *QueryContainmentAllowlistRulesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query containment allowlist rules internal server error response has a 4xx status code
func (o *QueryContainmentAllowlistRulesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this query containment allowlist rules internal server error response has a 5xx status code
func (o *QueryContainmentAllowlistRulesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this query containment allowlist rules internal server error response a status code equal to that given
func (o *QueryContainmentAllowlistRulesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the query containment allowlist rules internal server error response
func (o *QueryContainmentAllowlistRulesInternalServerError) Code() int {
	return 500
}

func (o *QueryContainmentAllowlistRulesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /customers/queries/containment-allowlist-rules/v1][%d] queryContainmentAllowlistRulesInternalServerError  %+v", 500, o.Payload)
}

func (o *QueryContainmentAllowlistRulesInternalServerError) String() string {
	return fmt.Sprintf("[GET /customers/queries/containment-allowlist-rules/v1][%d] queryContainmentAllowlistRulesInternalServerError  %+v", 500, o.Payload)
}

func (o *QueryContainmentAllowlistRulesInternalServerError) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *QueryContainmentAllowlistRulesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
