// Code generated by go-swagger; DO NOT EDIT.

package it_automation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// NewITAutomationCancelTaskExecutionParams creates a new ITAutomationCancelTaskExecutionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewITAutomationCancelTaskExecutionParams() *ITAutomationCancelTaskExecutionParams {
	return &ITAutomationCancelTaskExecutionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewITAutomationCancelTaskExecutionParamsWithTimeout creates a new ITAutomationCancelTaskExecutionParams object
// with the ability to set a timeout on a request.
func NewITAutomationCancelTaskExecutionParamsWithTimeout(timeout time.Duration) *ITAutomationCancelTaskExecutionParams {
	return &ITAutomationCancelTaskExecutionParams{
		timeout: timeout,
	}
}

// NewITAutomationCancelTaskExecutionParamsWithContext creates a new ITAutomationCancelTaskExecutionParams object
// with the ability to set a context for a request.
func NewITAutomationCancelTaskExecutionParamsWithContext(ctx context.Context) *ITAutomationCancelTaskExecutionParams {
	return &ITAutomationCancelTaskExecutionParams{
		Context: ctx,
	}
}

// NewITAutomationCancelTaskExecutionParamsWithHTTPClient creates a new ITAutomationCancelTaskExecutionParams object
// with the ability to set a custom HTTPClient for a request.
func NewITAutomationCancelTaskExecutionParamsWithHTTPClient(client *http.Client) *ITAutomationCancelTaskExecutionParams {
	return &ITAutomationCancelTaskExecutionParams{
		HTTPClient: client,
	}
}

/*
ITAutomationCancelTaskExecutionParams contains all the parameters to send to the API endpoint

	for the i t automation cancel task execution operation.

	Typically these are written to a http.Request.
*/
type ITAutomationCancelTaskExecutionParams struct {

	// Body.
	Body *models.ItautomationCancelTaskExecutionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the i t automation cancel task execution params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ITAutomationCancelTaskExecutionParams) WithDefaults() *ITAutomationCancelTaskExecutionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the i t automation cancel task execution params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ITAutomationCancelTaskExecutionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the i t automation cancel task execution params
func (o *ITAutomationCancelTaskExecutionParams) WithTimeout(timeout time.Duration) *ITAutomationCancelTaskExecutionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the i t automation cancel task execution params
func (o *ITAutomationCancelTaskExecutionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the i t automation cancel task execution params
func (o *ITAutomationCancelTaskExecutionParams) WithContext(ctx context.Context) *ITAutomationCancelTaskExecutionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the i t automation cancel task execution params
func (o *ITAutomationCancelTaskExecutionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the i t automation cancel task execution params
func (o *ITAutomationCancelTaskExecutionParams) WithHTTPClient(client *http.Client) *ITAutomationCancelTaskExecutionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the i t automation cancel task execution params
func (o *ITAutomationCancelTaskExecutionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the i t automation cancel task execution params
func (o *ITAutomationCancelTaskExecutionParams) WithBody(body *models.ItautomationCancelTaskExecutionRequest) *ITAutomationCancelTaskExecutionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the i t automation cancel task execution params
func (o *ITAutomationCancelTaskExecutionParams) SetBody(body *models.ItautomationCancelTaskExecutionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ITAutomationCancelTaskExecutionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
