// Code generated by go-swagger; DO NOT EDIT.

package network_scan_networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new network scan networks API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for network scan networks API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AggregateNetworks(params *AggregateNetworksParams, opts ...ClientOption) (*AggregateNetworksOK, error)

	CreateNetworks(params *CreateNetworksParams, opts ...ClientOption) (*CreateNetworksCreated, error)

	DeleteNetworks(params *DeleteNetworksParams, opts ...ClientOption) (*DeleteNetworksOK, error)

	GetNetworks(params *GetNetworksParams, opts ...ClientOption) (*GetNetworksOK, error)

	QueryNetworks(params *QueryNetworksParams, opts ...ClientOption) (*QueryNetworksOK, error)

	UpdateNetworks(params *UpdateNetworksParams, opts ...ClientOption) (*UpdateNetworksOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
AggregateNetworks returns networks aggregations
*/
func (a *Client) AggregateNetworks(params *AggregateNetworksParams, opts ...ClientOption) (*AggregateNetworksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAggregateNetworksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "aggregate-networks",
		Method:             "POST",
		PathPattern:        "/netscan/aggregates/networks/GET/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AggregateNetworksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AggregateNetworksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for aggregate-networks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
CreateNetworks creates networks using provided specifications
*/
func (a *Client) CreateNetworks(params *CreateNetworksParams, opts ...ClientOption) (*CreateNetworksCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateNetworksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "create-networks",
		Method:             "POST",
		PathPattern:        "/netscan/entities/networks/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateNetworksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateNetworksCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for create-networks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteNetworks deletes networks by their i ds
*/
func (a *Client) DeleteNetworks(params *DeleteNetworksParams, opts ...ClientOption) (*DeleteNetworksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteNetworksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "delete-networks",
		Method:             "DELETE",
		PathPattern:        "/netscan/entities/networks/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteNetworksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteNetworksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for delete-networks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetNetworks gets networks by their i ds
*/
func (a *Client) GetNetworks(params *GetNetworksParams, opts ...ClientOption) (*GetNetworksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetNetworksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get-networks",
		Method:             "GET",
		PathPattern:        "/netscan/entities/networks/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetNetworksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetNetworksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get-networks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
QueryNetworks gets networks i ds by filter
*/
func (a *Client) QueryNetworks(params *QueryNetworksParams, opts ...ClientOption) (*QueryNetworksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQueryNetworksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "query-networks",
		Method:             "GET",
		PathPattern:        "/netscan/queries/networks/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &QueryNetworksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*QueryNetworksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for query-networks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateNetworks updates networks using provided specifications
*/
func (a *Client) UpdateNetworks(params *UpdateNetworksParams, opts ...ClientOption) (*UpdateNetworksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateNetworksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "update-networks",
		Method:             "PATCH",
		PathPattern:        "/netscan/entities/networks/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdateNetworksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateNetworksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for update-networks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
