// Code generated by go-swagger; DO NOT EDIT.

package kubernetes_protection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/aslape/gofalcon/falcon/models"
)

// DistinctContainerImageCountReader is a Reader for the DistinctContainerImageCount structure.
type DistinctContainerImageCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DistinctContainerImageCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDistinctContainerImageCountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDistinctContainerImageCountForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDistinctContainerImageCountTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDistinctContainerImageCountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /container-security/aggregates/images/count-by-distinct/v1] DistinctContainerImageCount", response, response.Code())
	}
}

// NewDistinctContainerImageCountOK creates a DistinctContainerImageCountOK with default headers values
func NewDistinctContainerImageCountOK() *DistinctContainerImageCountOK {
	return &DistinctContainerImageCountOK{}
}

/*
DistinctContainerImageCountOK describes a response with status code 200, with default header values.

OK
*/
type DistinctContainerImageCountOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.ModelsAPIFilterResponse
}

// IsSuccess returns true when this distinct container image count o k response has a 2xx status code
func (o *DistinctContainerImageCountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this distinct container image count o k response has a 3xx status code
func (o *DistinctContainerImageCountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this distinct container image count o k response has a 4xx status code
func (o *DistinctContainerImageCountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this distinct container image count o k response has a 5xx status code
func (o *DistinctContainerImageCountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this distinct container image count o k response a status code equal to that given
func (o *DistinctContainerImageCountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the distinct container image count o k response
func (o *DistinctContainerImageCountOK) Code() int {
	return 200
}

func (o *DistinctContainerImageCountOK) Error() string {
	return fmt.Sprintf("[GET /container-security/aggregates/images/count-by-distinct/v1][%d] distinctContainerImageCountOK  %+v", 200, o.Payload)
}

func (o *DistinctContainerImageCountOK) String() string {
	return fmt.Sprintf("[GET /container-security/aggregates/images/count-by-distinct/v1][%d] distinctContainerImageCountOK  %+v", 200, o.Payload)
}

func (o *DistinctContainerImageCountOK) GetPayload() *models.ModelsAPIFilterResponse {
	return o.Payload
}

func (o *DistinctContainerImageCountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.ModelsAPIFilterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistinctContainerImageCountForbidden creates a DistinctContainerImageCountForbidden with default headers values
func NewDistinctContainerImageCountForbidden() *DistinctContainerImageCountForbidden {
	return &DistinctContainerImageCountForbidden{}
}

/*
DistinctContainerImageCountForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DistinctContainerImageCountForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this distinct container image count forbidden response has a 2xx status code
func (o *DistinctContainerImageCountForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this distinct container image count forbidden response has a 3xx status code
func (o *DistinctContainerImageCountForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this distinct container image count forbidden response has a 4xx status code
func (o *DistinctContainerImageCountForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this distinct container image count forbidden response has a 5xx status code
func (o *DistinctContainerImageCountForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this distinct container image count forbidden response a status code equal to that given
func (o *DistinctContainerImageCountForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the distinct container image count forbidden response
func (o *DistinctContainerImageCountForbidden) Code() int {
	return 403
}

func (o *DistinctContainerImageCountForbidden) Error() string {
	return fmt.Sprintf("[GET /container-security/aggregates/images/count-by-distinct/v1][%d] distinctContainerImageCountForbidden  %+v", 403, o.Payload)
}

func (o *DistinctContainerImageCountForbidden) String() string {
	return fmt.Sprintf("[GET /container-security/aggregates/images/count-by-distinct/v1][%d] distinctContainerImageCountForbidden  %+v", 403, o.Payload)
}

func (o *DistinctContainerImageCountForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *DistinctContainerImageCountForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistinctContainerImageCountTooManyRequests creates a DistinctContainerImageCountTooManyRequests with default headers values
func NewDistinctContainerImageCountTooManyRequests() *DistinctContainerImageCountTooManyRequests {
	return &DistinctContainerImageCountTooManyRequests{}
}

/*
DistinctContainerImageCountTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type DistinctContainerImageCountTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this distinct container image count too many requests response has a 2xx status code
func (o *DistinctContainerImageCountTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this distinct container image count too many requests response has a 3xx status code
func (o *DistinctContainerImageCountTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this distinct container image count too many requests response has a 4xx status code
func (o *DistinctContainerImageCountTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this distinct container image count too many requests response has a 5xx status code
func (o *DistinctContainerImageCountTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this distinct container image count too many requests response a status code equal to that given
func (o *DistinctContainerImageCountTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the distinct container image count too many requests response
func (o *DistinctContainerImageCountTooManyRequests) Code() int {
	return 429
}

func (o *DistinctContainerImageCountTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /container-security/aggregates/images/count-by-distinct/v1][%d] distinctContainerImageCountTooManyRequests  %+v", 429, o.Payload)
}

func (o *DistinctContainerImageCountTooManyRequests) String() string {
	return fmt.Sprintf("[GET /container-security/aggregates/images/count-by-distinct/v1][%d] distinctContainerImageCountTooManyRequests  %+v", 429, o.Payload)
}

func (o *DistinctContainerImageCountTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *DistinctContainerImageCountTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDistinctContainerImageCountInternalServerError creates a DistinctContainerImageCountInternalServerError with default headers values
func NewDistinctContainerImageCountInternalServerError() *DistinctContainerImageCountInternalServerError {
	return &DistinctContainerImageCountInternalServerError{}
}

/*
DistinctContainerImageCountInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DistinctContainerImageCountInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.CoreEntitiesResponse
}

// IsSuccess returns true when this distinct container image count internal server error response has a 2xx status code
func (o *DistinctContainerImageCountInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this distinct container image count internal server error response has a 3xx status code
func (o *DistinctContainerImageCountInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this distinct container image count internal server error response has a 4xx status code
func (o *DistinctContainerImageCountInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this distinct container image count internal server error response has a 5xx status code
func (o *DistinctContainerImageCountInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this distinct container image count internal server error response a status code equal to that given
func (o *DistinctContainerImageCountInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the distinct container image count internal server error response
func (o *DistinctContainerImageCountInternalServerError) Code() int {
	return 500
}

func (o *DistinctContainerImageCountInternalServerError) Error() string {
	return fmt.Sprintf("[GET /container-security/aggregates/images/count-by-distinct/v1][%d] distinctContainerImageCountInternalServerError  %+v", 500, o.Payload)
}

func (o *DistinctContainerImageCountInternalServerError) String() string {
	return fmt.Sprintf("[GET /container-security/aggregates/images/count-by-distinct/v1][%d] distinctContainerImageCountInternalServerError  %+v", 500, o.Payload)
}

func (o *DistinctContainerImageCountInternalServerError) GetPayload() *models.CoreEntitiesResponse {
	return o.Payload
}

func (o *DistinctContainerImageCountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.CoreEntitiesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
