// Code generated by go-swagger; DO NOT EDIT.

package kubernetes_protection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStaticScriptsParams creates a new GetStaticScriptsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStaticScriptsParams() *GetStaticScriptsParams {
	return &GetStaticScriptsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStaticScriptsParamsWithTimeout creates a new GetStaticScriptsParams object
// with the ability to set a timeout on a request.
func NewGetStaticScriptsParamsWithTimeout(timeout time.Duration) *GetStaticScriptsParams {
	return &GetStaticScriptsParams{
		timeout: timeout,
	}
}

// NewGetStaticScriptsParamsWithContext creates a new GetStaticScriptsParams object
// with the ability to set a context for a request.
func NewGetStaticScriptsParamsWithContext(ctx context.Context) *GetStaticScriptsParams {
	return &GetStaticScriptsParams{
		Context: ctx,
	}
}

// NewGetStaticScriptsParamsWithHTTPClient creates a new GetStaticScriptsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStaticScriptsParamsWithHTTPClient(client *http.Client) *GetStaticScriptsParams {
	return &GetStaticScriptsParams{
		HTTPClient: client,
	}
}

/* GetStaticScriptsParams contains all the parameters to send to the API endpoint
   for the get static scripts operation.

   Typically these are written to a http.Request.
*/
type GetStaticScriptsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get static scripts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStaticScriptsParams) WithDefaults() *GetStaticScriptsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get static scripts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStaticScriptsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get static scripts params
func (o *GetStaticScriptsParams) WithTimeout(timeout time.Duration) *GetStaticScriptsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get static scripts params
func (o *GetStaticScriptsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get static scripts params
func (o *GetStaticScriptsParams) WithContext(ctx context.Context) *GetStaticScriptsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get static scripts params
func (o *GetStaticScriptsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get static scripts params
func (o *GetStaticScriptsParams) WithHTTPClient(client *http.Client) *GetStaticScriptsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get static scripts params
func (o *GetStaticScriptsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetStaticScriptsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
