// Code generated by go-swagger; DO NOT EDIT.

package network_scan_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// GetZonesReader is a Reader for the GetZones structure.
type GetZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetZonesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetZonesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetZonesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetZonesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetZonesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /netscan/entities/zones/v1] get-zones", response, response.Code())
	}
}

// NewGetZonesOK creates a GetZonesOK with default headers values
func NewGetZonesOK() *GetZonesOK {
	return &GetZonesOK{}
}

/*
GetZonesOK describes a response with status code 200, with default header values.

OK
*/
type GetZonesOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.DomainZoneEntitiesResponse
}

// IsSuccess returns true when this get zones o k response has a 2xx status code
func (o *GetZonesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get zones o k response has a 3xx status code
func (o *GetZonesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get zones o k response has a 4xx status code
func (o *GetZonesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get zones o k response has a 5xx status code
func (o *GetZonesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get zones o k response a status code equal to that given
func (o *GetZonesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get zones o k response
func (o *GetZonesOK) Code() int {
	return 200
}

func (o *GetZonesOK) Error() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesOK  %+v", 200, o.Payload)
}

func (o *GetZonesOK) String() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesOK  %+v", 200, o.Payload)
}

func (o *GetZonesOK) GetPayload() *models.DomainZoneEntitiesResponse {
	return o.Payload
}

func (o *GetZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.DomainZoneEntitiesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesBadRequest creates a GetZonesBadRequest with default headers values
func NewGetZonesBadRequest() *GetZonesBadRequest {
	return &GetZonesBadRequest{}
}

/*
GetZonesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetZonesBadRequest struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this get zones bad request response has a 2xx status code
func (o *GetZonesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get zones bad request response has a 3xx status code
func (o *GetZonesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get zones bad request response has a 4xx status code
func (o *GetZonesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get zones bad request response has a 5xx status code
func (o *GetZonesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get zones bad request response a status code equal to that given
func (o *GetZonesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get zones bad request response
func (o *GetZonesBadRequest) Code() int {
	return 400
}

func (o *GetZonesBadRequest) Error() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesBadRequest  %+v", 400, o.Payload)
}

func (o *GetZonesBadRequest) String() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesBadRequest  %+v", 400, o.Payload)
}

func (o *GetZonesBadRequest) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *GetZonesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesForbidden creates a GetZonesForbidden with default headers values
func NewGetZonesForbidden() *GetZonesForbidden {
	return &GetZonesForbidden{}
}

/*
GetZonesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetZonesForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this get zones forbidden response has a 2xx status code
func (o *GetZonesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get zones forbidden response has a 3xx status code
func (o *GetZonesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get zones forbidden response has a 4xx status code
func (o *GetZonesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get zones forbidden response has a 5xx status code
func (o *GetZonesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get zones forbidden response a status code equal to that given
func (o *GetZonesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get zones forbidden response
func (o *GetZonesForbidden) Code() int {
	return 403
}

func (o *GetZonesForbidden) Error() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesForbidden  %+v", 403, o.Payload)
}

func (o *GetZonesForbidden) String() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesForbidden  %+v", 403, o.Payload)
}

func (o *GetZonesForbidden) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *GetZonesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesNotFound creates a GetZonesNotFound with default headers values
func NewGetZonesNotFound() *GetZonesNotFound {
	return &GetZonesNotFound{}
}

/*
GetZonesNotFound describes a response with status code 404, with default header values.

Forbidden
*/
type GetZonesNotFound struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this get zones not found response has a 2xx status code
func (o *GetZonesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get zones not found response has a 3xx status code
func (o *GetZonesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get zones not found response has a 4xx status code
func (o *GetZonesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get zones not found response has a 5xx status code
func (o *GetZonesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get zones not found response a status code equal to that given
func (o *GetZonesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get zones not found response
func (o *GetZonesNotFound) Code() int {
	return 404
}

func (o *GetZonesNotFound) Error() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesNotFound  %+v", 404, o.Payload)
}

func (o *GetZonesNotFound) String() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesNotFound  %+v", 404, o.Payload)
}

func (o *GetZonesNotFound) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *GetZonesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesTooManyRequests creates a GetZonesTooManyRequests with default headers values
func NewGetZonesTooManyRequests() *GetZonesTooManyRequests {
	return &GetZonesTooManyRequests{}
}

/*
GetZonesTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetZonesTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get zones too many requests response has a 2xx status code
func (o *GetZonesTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get zones too many requests response has a 3xx status code
func (o *GetZonesTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get zones too many requests response has a 4xx status code
func (o *GetZonesTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get zones too many requests response has a 5xx status code
func (o *GetZonesTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get zones too many requests response a status code equal to that given
func (o *GetZonesTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get zones too many requests response
func (o *GetZonesTooManyRequests) Code() int {
	return 429
}

func (o *GetZonesTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetZonesTooManyRequests) String() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetZonesTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetZonesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesInternalServerError creates a GetZonesInternalServerError with default headers values
func NewGetZonesInternalServerError() *GetZonesInternalServerError {
	return &GetZonesInternalServerError{}
}

/*
GetZonesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetZonesInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this get zones internal server error response has a 2xx status code
func (o *GetZonesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get zones internal server error response has a 3xx status code
func (o *GetZonesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get zones internal server error response has a 4xx status code
func (o *GetZonesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get zones internal server error response has a 5xx status code
func (o *GetZonesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get zones internal server error response a status code equal to that given
func (o *GetZonesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get zones internal server error response
func (o *GetZonesInternalServerError) Code() int {
	return 500
}

func (o *GetZonesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetZonesInternalServerError) String() string {
	return fmt.Sprintf("[GET /netscan/entities/zones/v1][%d] getZonesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetZonesInternalServerError) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *GetZonesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
