// Code generated by go-swagger; DO NOT EDIT.

package network_scan_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new network scan templates API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for network scan templates API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateTemplates(params *CreateTemplatesParams, opts ...ClientOption) (*CreateTemplatesCreated, error)

	DeleteTemplates(params *DeleteTemplatesParams, opts ...ClientOption) (*DeleteTemplatesOK, error)

	GetTemplateConfigs(params *GetTemplateConfigsParams, opts ...ClientOption) (*GetTemplateConfigsOK, error)

	GetTemplates(params *GetTemplatesParams, opts ...ClientOption) (*GetTemplatesOK, error)

	QueryTemplates(params *QueryTemplatesParams, opts ...ClientOption) (*QueryTemplatesOK, error)

	UpdateTemplates(params *UpdateTemplatesParams, opts ...ClientOption) (*UpdateTemplatesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateTemplates creates templates using provided specifications
*/
func (a *Client) CreateTemplates(params *CreateTemplatesParams, opts ...ClientOption) (*CreateTemplatesCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateTemplatesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "create-templates",
		Method:             "POST",
		PathPattern:        "/netscan/entities/templates/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateTemplatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateTemplatesCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for create-templates: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteTemplates deletes templates by their i ds
*/
func (a *Client) DeleteTemplates(params *DeleteTemplatesParams, opts ...ClientOption) (*DeleteTemplatesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteTemplatesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "delete-templates",
		Method:             "DELETE",
		PathPattern:        "/netscan/entities/templates/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteTemplatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteTemplatesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for delete-templates: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetTemplateConfigs gets details on the network scan template configurations
*/
func (a *Client) GetTemplateConfigs(params *GetTemplateConfigsParams, opts ...ClientOption) (*GetTemplateConfigsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTemplateConfigsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get-template-configs",
		Method:             "GET",
		PathPattern:        "/netscan/entities/template-configs/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetTemplateConfigsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTemplateConfigsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get-template-configs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetTemplates gets templates by their i ds
*/
func (a *Client) GetTemplates(params *GetTemplatesParams, opts ...ClientOption) (*GetTemplatesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTemplatesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get-templates",
		Method:             "GET",
		PathPattern:        "/netscan/entities/templates/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetTemplatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTemplatesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get-templates: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
QueryTemplates gets templates i ds by filter
*/
func (a *Client) QueryTemplates(params *QueryTemplatesParams, opts ...ClientOption) (*QueryTemplatesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQueryTemplatesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "query-templates",
		Method:             "GET",
		PathPattern:        "/netscan/queries/templates/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &QueryTemplatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*QueryTemplatesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for query-templates: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateTemplates updates templates using provided specifications
*/
func (a *Client) UpdateTemplates(params *UpdateTemplatesParams, opts ...ClientOption) (*UpdateTemplatesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateTemplatesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "update-templates",
		Method:             "PATCH",
		PathPattern:        "/netscan/entities/templates/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdateTemplatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateTemplatesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for update-templates: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
