// Code generated by go-swagger; DO NOT EDIT.

package ngsiem

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// NewBulkCreateDashboardsFromTemplateParams creates a new BulkCreateDashboardsFromTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBulkCreateDashboardsFromTemplateParams() *BulkCreateDashboardsFromTemplateParams {
	return &BulkCreateDashboardsFromTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBulkCreateDashboardsFromTemplateParamsWithTimeout creates a new BulkCreateDashboardsFromTemplateParams object
// with the ability to set a timeout on a request.
func NewBulkCreateDashboardsFromTemplateParamsWithTimeout(timeout time.Duration) *BulkCreateDashboardsFromTemplateParams {
	return &BulkCreateDashboardsFromTemplateParams{
		timeout: timeout,
	}
}

// NewBulkCreateDashboardsFromTemplateParamsWithContext creates a new BulkCreateDashboardsFromTemplateParams object
// with the ability to set a context for a request.
func NewBulkCreateDashboardsFromTemplateParamsWithContext(ctx context.Context) *BulkCreateDashboardsFromTemplateParams {
	return &BulkCreateDashboardsFromTemplateParams{
		Context: ctx,
	}
}

// NewBulkCreateDashboardsFromTemplateParamsWithHTTPClient creates a new BulkCreateDashboardsFromTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewBulkCreateDashboardsFromTemplateParamsWithHTTPClient(client *http.Client) *BulkCreateDashboardsFromTemplateParams {
	return &BulkCreateDashboardsFromTemplateParams{
		HTTPClient: client,
	}
}

/*
BulkCreateDashboardsFromTemplateParams contains all the parameters to send to the API endpoint

	for the bulk create dashboards from template operation.

	Typically these are written to a http.Request.
*/
type BulkCreateDashboardsFromTemplateParams struct {

	// Body.
	Body *models.APIBulkCreateDashboardsFromTemplateRequestV1

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bulk create dashboards from template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkCreateDashboardsFromTemplateParams) WithDefaults() *BulkCreateDashboardsFromTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bulk create dashboards from template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkCreateDashboardsFromTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bulk create dashboards from template params
func (o *BulkCreateDashboardsFromTemplateParams) WithTimeout(timeout time.Duration) *BulkCreateDashboardsFromTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bulk create dashboards from template params
func (o *BulkCreateDashboardsFromTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bulk create dashboards from template params
func (o *BulkCreateDashboardsFromTemplateParams) WithContext(ctx context.Context) *BulkCreateDashboardsFromTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bulk create dashboards from template params
func (o *BulkCreateDashboardsFromTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bulk create dashboards from template params
func (o *BulkCreateDashboardsFromTemplateParams) WithHTTPClient(client *http.Client) *BulkCreateDashboardsFromTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bulk create dashboards from template params
func (o *BulkCreateDashboardsFromTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the bulk create dashboards from template params
func (o *BulkCreateDashboardsFromTemplateParams) WithBody(body *models.APIBulkCreateDashboardsFromTemplateRequestV1) *BulkCreateDashboardsFromTemplateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the bulk create dashboards from template params
func (o *BulkCreateDashboardsFromTemplateParams) SetBody(body *models.APIBulkCreateDashboardsFromTemplateRequestV1) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *BulkCreateDashboardsFromTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
