// Code generated by go-swagger; DO NOT EDIT.

package ngsiem

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// BulkUpdateDashboardLabelsReader is a Reader for the BulkUpdateDashboardLabels structure.
type BulkUpdateDashboardLabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BulkUpdateDashboardLabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBulkUpdateDashboardLabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBulkUpdateDashboardLabelsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewBulkUpdateDashboardLabelsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewBulkUpdateDashboardLabelsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBulkUpdateDashboardLabelsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewBulkUpdateDashboardLabelsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBulkUpdateDashboardLabelsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1] bulkUpdateDashboardLabels", response, response.Code())
	}
}

// NewBulkUpdateDashboardLabelsOK creates a BulkUpdateDashboardLabelsOK with default headers values
func NewBulkUpdateDashboardLabelsOK() *BulkUpdateDashboardLabelsOK {
	return &BulkUpdateDashboardLabelsOK{}
}

/*
BulkUpdateDashboardLabelsOK describes a response with status code 200, with default header values.

BulkUpdateDashboardLabelsOK bulk update dashboard labels o k
*/
type BulkUpdateDashboardLabelsOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.APIBulkDashboardLabelsResponseV1
}

// IsSuccess returns true when this bulk update dashboard labels o k response has a 2xx status code
func (o *BulkUpdateDashboardLabelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this bulk update dashboard labels o k response has a 3xx status code
func (o *BulkUpdateDashboardLabelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk update dashboard labels o k response has a 4xx status code
func (o *BulkUpdateDashboardLabelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this bulk update dashboard labels o k response has a 5xx status code
func (o *BulkUpdateDashboardLabelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk update dashboard labels o k response a status code equal to that given
func (o *BulkUpdateDashboardLabelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the bulk update dashboard labels o k response
func (o *BulkUpdateDashboardLabelsOK) Code() int {
	return 200
}

func (o *BulkUpdateDashboardLabelsOK) Error() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsOK  %+v", 200, o.Payload)
}

func (o *BulkUpdateDashboardLabelsOK) String() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsOK  %+v", 200, o.Payload)
}

func (o *BulkUpdateDashboardLabelsOK) GetPayload() *models.APIBulkDashboardLabelsResponseV1 {
	return o.Payload
}

func (o *BulkUpdateDashboardLabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.APIBulkDashboardLabelsResponseV1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkUpdateDashboardLabelsBadRequest creates a BulkUpdateDashboardLabelsBadRequest with default headers values
func NewBulkUpdateDashboardLabelsBadRequest() *BulkUpdateDashboardLabelsBadRequest {
	return &BulkUpdateDashboardLabelsBadRequest{}
}

/*
BulkUpdateDashboardLabelsBadRequest describes a response with status code 400, with default header values.

Bad request for content operations
*/
type BulkUpdateDashboardLabelsBadRequest struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this bulk update dashboard labels bad request response has a 2xx status code
func (o *BulkUpdateDashboardLabelsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk update dashboard labels bad request response has a 3xx status code
func (o *BulkUpdateDashboardLabelsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk update dashboard labels bad request response has a 4xx status code
func (o *BulkUpdateDashboardLabelsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk update dashboard labels bad request response has a 5xx status code
func (o *BulkUpdateDashboardLabelsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk update dashboard labels bad request response a status code equal to that given
func (o *BulkUpdateDashboardLabelsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the bulk update dashboard labels bad request response
func (o *BulkUpdateDashboardLabelsBadRequest) Code() int {
	return 400
}

func (o *BulkUpdateDashboardLabelsBadRequest) Error() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsBadRequest  %+v", 400, o.Payload)
}

func (o *BulkUpdateDashboardLabelsBadRequest) String() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsBadRequest  %+v", 400, o.Payload)
}

func (o *BulkUpdateDashboardLabelsBadRequest) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *BulkUpdateDashboardLabelsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkUpdateDashboardLabelsUnauthorized creates a BulkUpdateDashboardLabelsUnauthorized with default headers values
func NewBulkUpdateDashboardLabelsUnauthorized() *BulkUpdateDashboardLabelsUnauthorized {
	return &BulkUpdateDashboardLabelsUnauthorized{}
}

/*
BulkUpdateDashboardLabelsUnauthorized describes a response with status code 401, with default header values.

Requestor is not authorized to access resource
*/
type BulkUpdateDashboardLabelsUnauthorized struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this bulk update dashboard labels unauthorized response has a 2xx status code
func (o *BulkUpdateDashboardLabelsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk update dashboard labels unauthorized response has a 3xx status code
func (o *BulkUpdateDashboardLabelsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk update dashboard labels unauthorized response has a 4xx status code
func (o *BulkUpdateDashboardLabelsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk update dashboard labels unauthorized response has a 5xx status code
func (o *BulkUpdateDashboardLabelsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk update dashboard labels unauthorized response a status code equal to that given
func (o *BulkUpdateDashboardLabelsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the bulk update dashboard labels unauthorized response
func (o *BulkUpdateDashboardLabelsUnauthorized) Code() int {
	return 401
}

func (o *BulkUpdateDashboardLabelsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsUnauthorized  %+v", 401, o.Payload)
}

func (o *BulkUpdateDashboardLabelsUnauthorized) String() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsUnauthorized  %+v", 401, o.Payload)
}

func (o *BulkUpdateDashboardLabelsUnauthorized) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *BulkUpdateDashboardLabelsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkUpdateDashboardLabelsForbidden creates a BulkUpdateDashboardLabelsForbidden with default headers values
func NewBulkUpdateDashboardLabelsForbidden() *BulkUpdateDashboardLabelsForbidden {
	return &BulkUpdateDashboardLabelsForbidden{}
}

/*
BulkUpdateDashboardLabelsForbidden describes a response with status code 403, with default header values.

Content access is not allowed
*/
type BulkUpdateDashboardLabelsForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this bulk update dashboard labels forbidden response has a 2xx status code
func (o *BulkUpdateDashboardLabelsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk update dashboard labels forbidden response has a 3xx status code
func (o *BulkUpdateDashboardLabelsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk update dashboard labels forbidden response has a 4xx status code
func (o *BulkUpdateDashboardLabelsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk update dashboard labels forbidden response has a 5xx status code
func (o *BulkUpdateDashboardLabelsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk update dashboard labels forbidden response a status code equal to that given
func (o *BulkUpdateDashboardLabelsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the bulk update dashboard labels forbidden response
func (o *BulkUpdateDashboardLabelsForbidden) Code() int {
	return 403
}

func (o *BulkUpdateDashboardLabelsForbidden) Error() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsForbidden  %+v", 403, o.Payload)
}

func (o *BulkUpdateDashboardLabelsForbidden) String() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsForbidden  %+v", 403, o.Payload)
}

func (o *BulkUpdateDashboardLabelsForbidden) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *BulkUpdateDashboardLabelsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkUpdateDashboardLabelsNotFound creates a BulkUpdateDashboardLabelsNotFound with default headers values
func NewBulkUpdateDashboardLabelsNotFound() *BulkUpdateDashboardLabelsNotFound {
	return &BulkUpdateDashboardLabelsNotFound{}
}

/*
BulkUpdateDashboardLabelsNotFound describes a response with status code 404, with default header values.

Content resource does not exist
*/
type BulkUpdateDashboardLabelsNotFound struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this bulk update dashboard labels not found response has a 2xx status code
func (o *BulkUpdateDashboardLabelsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk update dashboard labels not found response has a 3xx status code
func (o *BulkUpdateDashboardLabelsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk update dashboard labels not found response has a 4xx status code
func (o *BulkUpdateDashboardLabelsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk update dashboard labels not found response has a 5xx status code
func (o *BulkUpdateDashboardLabelsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk update dashboard labels not found response a status code equal to that given
func (o *BulkUpdateDashboardLabelsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the bulk update dashboard labels not found response
func (o *BulkUpdateDashboardLabelsNotFound) Code() int {
	return 404
}

func (o *BulkUpdateDashboardLabelsNotFound) Error() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsNotFound  %+v", 404, o.Payload)
}

func (o *BulkUpdateDashboardLabelsNotFound) String() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsNotFound  %+v", 404, o.Payload)
}

func (o *BulkUpdateDashboardLabelsNotFound) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *BulkUpdateDashboardLabelsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkUpdateDashboardLabelsTooManyRequests creates a BulkUpdateDashboardLabelsTooManyRequests with default headers values
func NewBulkUpdateDashboardLabelsTooManyRequests() *BulkUpdateDashboardLabelsTooManyRequests {
	return &BulkUpdateDashboardLabelsTooManyRequests{}
}

/*
BulkUpdateDashboardLabelsTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type BulkUpdateDashboardLabelsTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this bulk update dashboard labels too many requests response has a 2xx status code
func (o *BulkUpdateDashboardLabelsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk update dashboard labels too many requests response has a 3xx status code
func (o *BulkUpdateDashboardLabelsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk update dashboard labels too many requests response has a 4xx status code
func (o *BulkUpdateDashboardLabelsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk update dashboard labels too many requests response has a 5xx status code
func (o *BulkUpdateDashboardLabelsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk update dashboard labels too many requests response a status code equal to that given
func (o *BulkUpdateDashboardLabelsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the bulk update dashboard labels too many requests response
func (o *BulkUpdateDashboardLabelsTooManyRequests) Code() int {
	return 429
}

func (o *BulkUpdateDashboardLabelsTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsTooManyRequests  %+v", 429, o.Payload)
}

func (o *BulkUpdateDashboardLabelsTooManyRequests) String() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsTooManyRequests  %+v", 429, o.Payload)
}

func (o *BulkUpdateDashboardLabelsTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *BulkUpdateDashboardLabelsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkUpdateDashboardLabelsInternalServerError creates a BulkUpdateDashboardLabelsInternalServerError with default headers values
func NewBulkUpdateDashboardLabelsInternalServerError() *BulkUpdateDashboardLabelsInternalServerError {
	return &BulkUpdateDashboardLabelsInternalServerError{}
}

/*
BulkUpdateDashboardLabelsInternalServerError describes a response with status code 500, with default header values.

Unexpected error occurred
*/
type BulkUpdateDashboardLabelsInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this bulk update dashboard labels internal server error response has a 2xx status code
func (o *BulkUpdateDashboardLabelsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk update dashboard labels internal server error response has a 3xx status code
func (o *BulkUpdateDashboardLabelsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk update dashboard labels internal server error response has a 4xx status code
func (o *BulkUpdateDashboardLabelsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this bulk update dashboard labels internal server error response has a 5xx status code
func (o *BulkUpdateDashboardLabelsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this bulk update dashboard labels internal server error response a status code equal to that given
func (o *BulkUpdateDashboardLabelsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the bulk update dashboard labels internal server error response
func (o *BulkUpdateDashboardLabelsInternalServerError) Code() int {
	return 500
}

func (o *BulkUpdateDashboardLabelsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsInternalServerError  %+v", 500, o.Payload)
}

func (o *BulkUpdateDashboardLabelsInternalServerError) String() string {
	return fmt.Sprintf("[POST /ngsiem-content/entities/bulk-dashboard-labels-replace/v1][%d] bulkUpdateDashboardLabelsInternalServerError  %+v", 500, o.Payload)
}

func (o *BulkUpdateDashboardLabelsInternalServerError) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *BulkUpdateDashboardLabelsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
