// Code generated by go-swagger; DO NOT EDIT.

package ngsiem

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// RemoveDashboardLabelsReader is a Reader for the RemoveDashboardLabels structure.
type RemoveDashboardLabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveDashboardLabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveDashboardLabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoveDashboardLabelsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewRemoveDashboardLabelsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRemoveDashboardLabelsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRemoveDashboardLabelsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewRemoveDashboardLabelsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoveDashboardLabelsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /ngsiem-content/entities/dashboard-labels/v1] removeDashboardLabels", response, response.Code())
	}
}

// NewRemoveDashboardLabelsOK creates a RemoveDashboardLabelsOK with default headers values
func NewRemoveDashboardLabelsOK() *RemoveDashboardLabelsOK {
	return &RemoveDashboardLabelsOK{}
}

/*
RemoveDashboardLabelsOK describes a response with status code 200, with default header values.

RemoveDashboardLabelsOK remove dashboard labels o k
*/
type RemoveDashboardLabelsOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.APILabelResponseV1
}

// IsSuccess returns true when this remove dashboard labels o k response has a 2xx status code
func (o *RemoveDashboardLabelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove dashboard labels o k response has a 3xx status code
func (o *RemoveDashboardLabelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove dashboard labels o k response has a 4xx status code
func (o *RemoveDashboardLabelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove dashboard labels o k response has a 5xx status code
func (o *RemoveDashboardLabelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this remove dashboard labels o k response a status code equal to that given
func (o *RemoveDashboardLabelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the remove dashboard labels o k response
func (o *RemoveDashboardLabelsOK) Code() int {
	return 200
}

func (o *RemoveDashboardLabelsOK) Error() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsOK  %+v", 200, o.Payload)
}

func (o *RemoveDashboardLabelsOK) String() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsOK  %+v", 200, o.Payload)
}

func (o *RemoveDashboardLabelsOK) GetPayload() *models.APILabelResponseV1 {
	return o.Payload
}

func (o *RemoveDashboardLabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.APILabelResponseV1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveDashboardLabelsBadRequest creates a RemoveDashboardLabelsBadRequest with default headers values
func NewRemoveDashboardLabelsBadRequest() *RemoveDashboardLabelsBadRequest {
	return &RemoveDashboardLabelsBadRequest{}
}

/*
RemoveDashboardLabelsBadRequest describes a response with status code 400, with default header values.

Bad request for content operations
*/
type RemoveDashboardLabelsBadRequest struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this remove dashboard labels bad request response has a 2xx status code
func (o *RemoveDashboardLabelsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove dashboard labels bad request response has a 3xx status code
func (o *RemoveDashboardLabelsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove dashboard labels bad request response has a 4xx status code
func (o *RemoveDashboardLabelsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove dashboard labels bad request response has a 5xx status code
func (o *RemoveDashboardLabelsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this remove dashboard labels bad request response a status code equal to that given
func (o *RemoveDashboardLabelsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the remove dashboard labels bad request response
func (o *RemoveDashboardLabelsBadRequest) Code() int {
	return 400
}

func (o *RemoveDashboardLabelsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsBadRequest  %+v", 400, o.Payload)
}

func (o *RemoveDashboardLabelsBadRequest) String() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsBadRequest  %+v", 400, o.Payload)
}

func (o *RemoveDashboardLabelsBadRequest) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *RemoveDashboardLabelsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveDashboardLabelsUnauthorized creates a RemoveDashboardLabelsUnauthorized with default headers values
func NewRemoveDashboardLabelsUnauthorized() *RemoveDashboardLabelsUnauthorized {
	return &RemoveDashboardLabelsUnauthorized{}
}

/*
RemoveDashboardLabelsUnauthorized describes a response with status code 401, with default header values.

Requestor is not authorized to access resource
*/
type RemoveDashboardLabelsUnauthorized struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this remove dashboard labels unauthorized response has a 2xx status code
func (o *RemoveDashboardLabelsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove dashboard labels unauthorized response has a 3xx status code
func (o *RemoveDashboardLabelsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove dashboard labels unauthorized response has a 4xx status code
func (o *RemoveDashboardLabelsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove dashboard labels unauthorized response has a 5xx status code
func (o *RemoveDashboardLabelsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this remove dashboard labels unauthorized response a status code equal to that given
func (o *RemoveDashboardLabelsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the remove dashboard labels unauthorized response
func (o *RemoveDashboardLabelsUnauthorized) Code() int {
	return 401
}

func (o *RemoveDashboardLabelsUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsUnauthorized  %+v", 401, o.Payload)
}

func (o *RemoveDashboardLabelsUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsUnauthorized  %+v", 401, o.Payload)
}

func (o *RemoveDashboardLabelsUnauthorized) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *RemoveDashboardLabelsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveDashboardLabelsForbidden creates a RemoveDashboardLabelsForbidden with default headers values
func NewRemoveDashboardLabelsForbidden() *RemoveDashboardLabelsForbidden {
	return &RemoveDashboardLabelsForbidden{}
}

/*
RemoveDashboardLabelsForbidden describes a response with status code 403, with default header values.

Content access is not allowed
*/
type RemoveDashboardLabelsForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this remove dashboard labels forbidden response has a 2xx status code
func (o *RemoveDashboardLabelsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove dashboard labels forbidden response has a 3xx status code
func (o *RemoveDashboardLabelsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove dashboard labels forbidden response has a 4xx status code
func (o *RemoveDashboardLabelsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove dashboard labels forbidden response has a 5xx status code
func (o *RemoveDashboardLabelsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this remove dashboard labels forbidden response a status code equal to that given
func (o *RemoveDashboardLabelsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the remove dashboard labels forbidden response
func (o *RemoveDashboardLabelsForbidden) Code() int {
	return 403
}

func (o *RemoveDashboardLabelsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsForbidden  %+v", 403, o.Payload)
}

func (o *RemoveDashboardLabelsForbidden) String() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsForbidden  %+v", 403, o.Payload)
}

func (o *RemoveDashboardLabelsForbidden) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *RemoveDashboardLabelsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveDashboardLabelsNotFound creates a RemoveDashboardLabelsNotFound with default headers values
func NewRemoveDashboardLabelsNotFound() *RemoveDashboardLabelsNotFound {
	return &RemoveDashboardLabelsNotFound{}
}

/*
RemoveDashboardLabelsNotFound describes a response with status code 404, with default header values.

Content resource does not exist
*/
type RemoveDashboardLabelsNotFound struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this remove dashboard labels not found response has a 2xx status code
func (o *RemoveDashboardLabelsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove dashboard labels not found response has a 3xx status code
func (o *RemoveDashboardLabelsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove dashboard labels not found response has a 4xx status code
func (o *RemoveDashboardLabelsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove dashboard labels not found response has a 5xx status code
func (o *RemoveDashboardLabelsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this remove dashboard labels not found response a status code equal to that given
func (o *RemoveDashboardLabelsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the remove dashboard labels not found response
func (o *RemoveDashboardLabelsNotFound) Code() int {
	return 404
}

func (o *RemoveDashboardLabelsNotFound) Error() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsNotFound  %+v", 404, o.Payload)
}

func (o *RemoveDashboardLabelsNotFound) String() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsNotFound  %+v", 404, o.Payload)
}

func (o *RemoveDashboardLabelsNotFound) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *RemoveDashboardLabelsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveDashboardLabelsTooManyRequests creates a RemoveDashboardLabelsTooManyRequests with default headers values
func NewRemoveDashboardLabelsTooManyRequests() *RemoveDashboardLabelsTooManyRequests {
	return &RemoveDashboardLabelsTooManyRequests{}
}

/*
RemoveDashboardLabelsTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type RemoveDashboardLabelsTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this remove dashboard labels too many requests response has a 2xx status code
func (o *RemoveDashboardLabelsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove dashboard labels too many requests response has a 3xx status code
func (o *RemoveDashboardLabelsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove dashboard labels too many requests response has a 4xx status code
func (o *RemoveDashboardLabelsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove dashboard labels too many requests response has a 5xx status code
func (o *RemoveDashboardLabelsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this remove dashboard labels too many requests response a status code equal to that given
func (o *RemoveDashboardLabelsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the remove dashboard labels too many requests response
func (o *RemoveDashboardLabelsTooManyRequests) Code() int {
	return 429
}

func (o *RemoveDashboardLabelsTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsTooManyRequests  %+v", 429, o.Payload)
}

func (o *RemoveDashboardLabelsTooManyRequests) String() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsTooManyRequests  %+v", 429, o.Payload)
}

func (o *RemoveDashboardLabelsTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *RemoveDashboardLabelsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveDashboardLabelsInternalServerError creates a RemoveDashboardLabelsInternalServerError with default headers values
func NewRemoveDashboardLabelsInternalServerError() *RemoveDashboardLabelsInternalServerError {
	return &RemoveDashboardLabelsInternalServerError{}
}

/*
RemoveDashboardLabelsInternalServerError describes a response with status code 500, with default header values.

Unexpected error occurred
*/
type RemoveDashboardLabelsInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this remove dashboard labels internal server error response has a 2xx status code
func (o *RemoveDashboardLabelsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove dashboard labels internal server error response has a 3xx status code
func (o *RemoveDashboardLabelsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove dashboard labels internal server error response has a 4xx status code
func (o *RemoveDashboardLabelsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove dashboard labels internal server error response has a 5xx status code
func (o *RemoveDashboardLabelsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this remove dashboard labels internal server error response a status code equal to that given
func (o *RemoveDashboardLabelsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the remove dashboard labels internal server error response
func (o *RemoveDashboardLabelsInternalServerError) Code() int {
	return 500
}

func (o *RemoveDashboardLabelsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsInternalServerError  %+v", 500, o.Payload)
}

func (o *RemoveDashboardLabelsInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /ngsiem-content/entities/dashboard-labels/v1][%d] removeDashboardLabelsInternalServerError  %+v", 500, o.Payload)
}

func (o *RemoveDashboardLabelsInternalServerError) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *RemoveDashboardLabelsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
