// Code generated by go-swagger; DO NOT EDIT.

package data_protection_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEntitiesPolicyDeleteV2Params creates a new EntitiesPolicyDeleteV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEntitiesPolicyDeleteV2Params() *EntitiesPolicyDeleteV2Params {
	return &EntitiesPolicyDeleteV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewEntitiesPolicyDeleteV2ParamsWithTimeout creates a new EntitiesPolicyDeleteV2Params object
// with the ability to set a timeout on a request.
func NewEntitiesPolicyDeleteV2ParamsWithTimeout(timeout time.Duration) *EntitiesPolicyDeleteV2Params {
	return &EntitiesPolicyDeleteV2Params{
		timeout: timeout,
	}
}

// NewEntitiesPolicyDeleteV2ParamsWithContext creates a new EntitiesPolicyDeleteV2Params object
// with the ability to set a context for a request.
func NewEntitiesPolicyDeleteV2ParamsWithContext(ctx context.Context) *EntitiesPolicyDeleteV2Params {
	return &EntitiesPolicyDeleteV2Params{
		Context: ctx,
	}
}

// NewEntitiesPolicyDeleteV2ParamsWithHTTPClient creates a new EntitiesPolicyDeleteV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewEntitiesPolicyDeleteV2ParamsWithHTTPClient(client *http.Client) *EntitiesPolicyDeleteV2Params {
	return &EntitiesPolicyDeleteV2Params{
		HTTPClient: client,
	}
}

/*
EntitiesPolicyDeleteV2Params contains all the parameters to send to the API endpoint

	for the entities policy delete v2 operation.

	Typically these are written to a http.Request.
*/
type EntitiesPolicyDeleteV2Params struct {

	/* Ids.

	   IDs of the policies to delete
	*/
	Ids []string

	/* PlatformName.

	   platform name of the policies to update, either 'win' or 'mac'
	*/
	PlatformName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the entities policy delete v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EntitiesPolicyDeleteV2Params) WithDefaults() *EntitiesPolicyDeleteV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the entities policy delete v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EntitiesPolicyDeleteV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) WithTimeout(timeout time.Duration) *EntitiesPolicyDeleteV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) WithContext(ctx context.Context) *EntitiesPolicyDeleteV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) WithHTTPClient(client *http.Client) *EntitiesPolicyDeleteV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) WithIds(ids []string) *EntitiesPolicyDeleteV2Params {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) SetIds(ids []string) {
	o.Ids = ids
}

// WithPlatformName adds the platformName to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) WithPlatformName(platformName string) *EntitiesPolicyDeleteV2Params {
	o.SetPlatformName(platformName)
	return o
}

// SetPlatformName adds the platformName to the entities policy delete v2 params
func (o *EntitiesPolicyDeleteV2Params) SetPlatformName(platformName string) {
	o.PlatformName = platformName
}

// WriteToRequest writes these params to a swagger request
func (o *EntitiesPolicyDeleteV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Ids != nil {

		// binding items for ids
		joinedIds := o.bindParamIds(reg)

		// query array param ids
		if err := r.SetQueryParam("ids", joinedIds...); err != nil {
			return err
		}
	}

	// query param platform_name
	qrPlatformName := o.PlatformName
	qPlatformName := qrPlatformName
	if qPlatformName != "" {

		if err := r.SetQueryParam("platform_name", qPlatformName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamEntitiesPolicyDeleteV2 binds the parameter ids
func (o *EntitiesPolicyDeleteV2Params) bindParamIds(formats strfmt.Registry) []string {
	idsIR := o.Ids

	var idsIC []string
	for _, idsIIR := range idsIR { // explode []string

		idsIIV := idsIIR // string as string
		idsIC = append(idsIC, idsIIV)
	}

	// items.CollectionFormat: "multi"
	idsIS := swag.JoinByFormat(idsIC, "multi")

	return idsIS
}
