// Code generated by go-swagger; DO NOT EDIT.

package humio_auth_proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLookupV1Params creates a new GetLookupV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLookupV1Params() *GetLookupV1Params {
	return &GetLookupV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLookupV1ParamsWithTimeout creates a new GetLookupV1Params object
// with the ability to set a timeout on a request.
func NewGetLookupV1ParamsWithTimeout(timeout time.Duration) *GetLookupV1Params {
	return &GetLookupV1Params{
		timeout: timeout,
	}
}

// NewGetLookupV1ParamsWithContext creates a new GetLookupV1Params object
// with the ability to set a context for a request.
func NewGetLookupV1ParamsWithContext(ctx context.Context) *GetLookupV1Params {
	return &GetLookupV1Params{
		Context: ctx,
	}
}

// NewGetLookupV1ParamsWithHTTPClient creates a new GetLookupV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetLookupV1ParamsWithHTTPClient(client *http.Client) *GetLookupV1Params {
	return &GetLookupV1Params{
		HTTPClient: client,
	}
}

/*
GetLookupV1Params contains all the parameters to send to the API endpoint

	for the get lookup v1 operation.

	Typically these are written to a http.Request.
*/
type GetLookupV1Params struct {

	/* Filename.

	   name of lookup file
	*/
	Filename string

	/* Repository.

	   name of repository
	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get lookup v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLookupV1Params) WithDefaults() *GetLookupV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get lookup v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLookupV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get lookup v1 params
func (o *GetLookupV1Params) WithTimeout(timeout time.Duration) *GetLookupV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lookup v1 params
func (o *GetLookupV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lookup v1 params
func (o *GetLookupV1Params) WithContext(ctx context.Context) *GetLookupV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lookup v1 params
func (o *GetLookupV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lookup v1 params
func (o *GetLookupV1Params) WithHTTPClient(client *http.Client) *GetLookupV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lookup v1 params
func (o *GetLookupV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilename adds the filename to the get lookup v1 params
func (o *GetLookupV1Params) WithFilename(filename string) *GetLookupV1Params {
	o.SetFilename(filename)
	return o
}

// SetFilename adds the filename to the get lookup v1 params
func (o *GetLookupV1Params) SetFilename(filename string) {
	o.Filename = filename
}

// WithRepository adds the repository to the get lookup v1 params
func (o *GetLookupV1Params) WithRepository(repository string) *GetLookupV1Params {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the get lookup v1 params
func (o *GetLookupV1Params) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *GetLookupV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param filename
	if err := r.SetPathParam("filename", o.Filename); err != nil {
		return err
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
