// Code generated by go-swagger; DO NOT EDIT.

package falcon_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// NewUpdateThirdPartyPasskeyRegistryParams creates a new UpdateThirdPartyPasskeyRegistryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateThirdPartyPasskeyRegistryParams() *UpdateThirdPartyPasskeyRegistryParams {
	return &UpdateThirdPartyPasskeyRegistryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateThirdPartyPasskeyRegistryParamsWithTimeout creates a new UpdateThirdPartyPasskeyRegistryParams object
// with the ability to set a timeout on a request.
func NewUpdateThirdPartyPasskeyRegistryParamsWithTimeout(timeout time.Duration) *UpdateThirdPartyPasskeyRegistryParams {
	return &UpdateThirdPartyPasskeyRegistryParams{
		timeout: timeout,
	}
}

// NewUpdateThirdPartyPasskeyRegistryParamsWithContext creates a new UpdateThirdPartyPasskeyRegistryParams object
// with the ability to set a context for a request.
func NewUpdateThirdPartyPasskeyRegistryParamsWithContext(ctx context.Context) *UpdateThirdPartyPasskeyRegistryParams {
	return &UpdateThirdPartyPasskeyRegistryParams{
		Context: ctx,
	}
}

// NewUpdateThirdPartyPasskeyRegistryParamsWithHTTPClient creates a new UpdateThirdPartyPasskeyRegistryParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateThirdPartyPasskeyRegistryParamsWithHTTPClient(client *http.Client) *UpdateThirdPartyPasskeyRegistryParams {
	return &UpdateThirdPartyPasskeyRegistryParams{
		HTTPClient: client,
	}
}

/*
UpdateThirdPartyPasskeyRegistryParams contains all the parameters to send to the API endpoint

	for the update third party passkey registry operation.

	Typically these are written to a http.Request.
*/
type UpdateThirdPartyPasskeyRegistryParams struct {

	// Body.
	Body []*models.FalconidapiThirdPartyPasskeyRegistryPatchRequestV1

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update third party passkey registry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateThirdPartyPasskeyRegistryParams) WithDefaults() *UpdateThirdPartyPasskeyRegistryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update third party passkey registry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateThirdPartyPasskeyRegistryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update third party passkey registry params
func (o *UpdateThirdPartyPasskeyRegistryParams) WithTimeout(timeout time.Duration) *UpdateThirdPartyPasskeyRegistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update third party passkey registry params
func (o *UpdateThirdPartyPasskeyRegistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update third party passkey registry params
func (o *UpdateThirdPartyPasskeyRegistryParams) WithContext(ctx context.Context) *UpdateThirdPartyPasskeyRegistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update third party passkey registry params
func (o *UpdateThirdPartyPasskeyRegistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update third party passkey registry params
func (o *UpdateThirdPartyPasskeyRegistryParams) WithHTTPClient(client *http.Client) *UpdateThirdPartyPasskeyRegistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update third party passkey registry params
func (o *UpdateThirdPartyPasskeyRegistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update third party passkey registry params
func (o *UpdateThirdPartyPasskeyRegistryParams) WithBody(body []*models.FalconidapiThirdPartyPasskeyRegistryPatchRequestV1) *UpdateThirdPartyPasskeyRegistryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update third party passkey registry params
func (o *UpdateThirdPartyPasskeyRegistryParams) SetBody(body []*models.FalconidapiThirdPartyPasskeyRegistryPatchRequestV1) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateThirdPartyPasskeyRegistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
