// Code generated by go-swagger; DO NOT EDIT.

package cloud_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewQuerySuppressionRulesParams creates a new QuerySuppressionRulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQuerySuppressionRulesParams() *QuerySuppressionRulesParams {
	return &QuerySuppressionRulesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQuerySuppressionRulesParamsWithTimeout creates a new QuerySuppressionRulesParams object
// with the ability to set a timeout on a request.
func NewQuerySuppressionRulesParamsWithTimeout(timeout time.Duration) *QuerySuppressionRulesParams {
	return &QuerySuppressionRulesParams{
		timeout: timeout,
	}
}

// NewQuerySuppressionRulesParamsWithContext creates a new QuerySuppressionRulesParams object
// with the ability to set a context for a request.
func NewQuerySuppressionRulesParamsWithContext(ctx context.Context) *QuerySuppressionRulesParams {
	return &QuerySuppressionRulesParams{
		Context: ctx,
	}
}

// NewQuerySuppressionRulesParamsWithHTTPClient creates a new QuerySuppressionRulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewQuerySuppressionRulesParamsWithHTTPClient(client *http.Client) *QuerySuppressionRulesParams {
	return &QuerySuppressionRulesParams{
		HTTPClient: client,
	}
}

/*
QuerySuppressionRulesParams contains all the parameters to send to the API endpoint

	for the query suppression rules operation.

	Typically these are written to a http.Request.
*/
type QuerySuppressionRulesParams struct {

	/* Filter.

	     FQL expression to filter suppression rules. The allowed properties are:

	*name*
	*description*
	*domain*
	*subdomain*
	*suppression_expiration_date*
	*suppression_reason*
	*created_by*
	*created_at*
	*last_modified_at*
	*disabled*
	*groups*

	*/
	Filter *string

	/* Limit.

	   The maximum number of resources to return. The maximum allowed is 50.

	   Default: 20
	*/
	Limit *int64

	/* Offset.

	   The number of results to skip before starting to return results.
	*/
	Offset *int64

	/* Sort.

	     Field to sort on. Sortable fields:

	*name*
	*description*
	*domain*
	*subdomain*
	*suppression_expiration_date*
	*suppression_reason*
	*created_by*
	*created_at*
	*last_modified_at*
	*disabled*
	*groups*


	Use the `.asc` or `.desc` suffix to specify sort direction.
	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query suppression rules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuerySuppressionRulesParams) WithDefaults() *QuerySuppressionRulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query suppression rules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuerySuppressionRulesParams) SetDefaults() {
	var (
		limitDefault = int64(20)

		offsetDefault = int64(0)
	)

	val := QuerySuppressionRulesParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the query suppression rules params
func (o *QuerySuppressionRulesParams) WithTimeout(timeout time.Duration) *QuerySuppressionRulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query suppression rules params
func (o *QuerySuppressionRulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query suppression rules params
func (o *QuerySuppressionRulesParams) WithContext(ctx context.Context) *QuerySuppressionRulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query suppression rules params
func (o *QuerySuppressionRulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query suppression rules params
func (o *QuerySuppressionRulesParams) WithHTTPClient(client *http.Client) *QuerySuppressionRulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query suppression rules params
func (o *QuerySuppressionRulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the query suppression rules params
func (o *QuerySuppressionRulesParams) WithFilter(filter *string) *QuerySuppressionRulesParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the query suppression rules params
func (o *QuerySuppressionRulesParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithLimit adds the limit to the query suppression rules params
func (o *QuerySuppressionRulesParams) WithLimit(limit *int64) *QuerySuppressionRulesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the query suppression rules params
func (o *QuerySuppressionRulesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the query suppression rules params
func (o *QuerySuppressionRulesParams) WithOffset(offset *int64) *QuerySuppressionRulesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the query suppression rules params
func (o *QuerySuppressionRulesParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSort adds the sort to the query suppression rules params
func (o *QuerySuppressionRulesParams) WithSort(sort *string) *QuerySuppressionRulesParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the query suppression rules params
func (o *QuerySuppressionRulesParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *QuerySuppressionRulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
