// Code generated by go-swagger; DO NOT EDIT.

package cases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// NewEntitiesAlertEvidencePostV1Params creates a new EntitiesAlertEvidencePostV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEntitiesAlertEvidencePostV1Params() *EntitiesAlertEvidencePostV1Params {
	return &EntitiesAlertEvidencePostV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewEntitiesAlertEvidencePostV1ParamsWithTimeout creates a new EntitiesAlertEvidencePostV1Params object
// with the ability to set a timeout on a request.
func NewEntitiesAlertEvidencePostV1ParamsWithTimeout(timeout time.Duration) *EntitiesAlertEvidencePostV1Params {
	return &EntitiesAlertEvidencePostV1Params{
		timeout: timeout,
	}
}

// NewEntitiesAlertEvidencePostV1ParamsWithContext creates a new EntitiesAlertEvidencePostV1Params object
// with the ability to set a context for a request.
func NewEntitiesAlertEvidencePostV1ParamsWithContext(ctx context.Context) *EntitiesAlertEvidencePostV1Params {
	return &EntitiesAlertEvidencePostV1Params{
		Context: ctx,
	}
}

// NewEntitiesAlertEvidencePostV1ParamsWithHTTPClient creates a new EntitiesAlertEvidencePostV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewEntitiesAlertEvidencePostV1ParamsWithHTTPClient(client *http.Client) *EntitiesAlertEvidencePostV1Params {
	return &EntitiesAlertEvidencePostV1Params{
		HTTPClient: client,
	}
}

/*
EntitiesAlertEvidencePostV1Params contains all the parameters to send to the API endpoint

	for the entities alert evidence post v1 operation.

	Typically these are written to a http.Request.
*/
type EntitiesAlertEvidencePostV1Params struct {

	// Body.
	Body *models.OperationsAddAlertsToCaseRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the entities alert evidence post v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EntitiesAlertEvidencePostV1Params) WithDefaults() *EntitiesAlertEvidencePostV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the entities alert evidence post v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EntitiesAlertEvidencePostV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the entities alert evidence post v1 params
func (o *EntitiesAlertEvidencePostV1Params) WithTimeout(timeout time.Duration) *EntitiesAlertEvidencePostV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the entities alert evidence post v1 params
func (o *EntitiesAlertEvidencePostV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the entities alert evidence post v1 params
func (o *EntitiesAlertEvidencePostV1Params) WithContext(ctx context.Context) *EntitiesAlertEvidencePostV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the entities alert evidence post v1 params
func (o *EntitiesAlertEvidencePostV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the entities alert evidence post v1 params
func (o *EntitiesAlertEvidencePostV1Params) WithHTTPClient(client *http.Client) *EntitiesAlertEvidencePostV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the entities alert evidence post v1 params
func (o *EntitiesAlertEvidencePostV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the entities alert evidence post v1 params
func (o *EntitiesAlertEvidencePostV1Params) WithBody(body *models.OperationsAddAlertsToCaseRequest) *EntitiesAlertEvidencePostV1Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the entities alert evidence post v1 params
func (o *EntitiesAlertEvidencePostV1Params) SetBody(body *models.OperationsAddAlertsToCaseRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EntitiesAlertEvidencePostV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
