name: gosec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.20.x]

    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run Gosec Security Scanner
      uses: securego/gosec@v2.22.2
      with:
        args: '-no-fail -fmt sarif -out results.sarif ./...'
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
