name: gosec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.16.x]

    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...
